# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Builtin plugin metadata catalogue.

Runtime plugins intentionally keep their execution logic small. This module owns
user-facing metadata used by ``automax plugins describe`` and generated docs so
that every builtin plugin exposes a complete, deterministic contract.
"""

from __future__ import annotations

from typing import Any

from automax.plugins.base import BasePlugin

PARAMETERS: dict[str, dict[str, Any]] = {
    "allow_replace_non_symlink": {"type": "boolean", "default": False, "description": "Allow force replacement when the destination exists and is not a symlink."},
    "algorithm": {"type": "string", "default": "sha256", "description": "Fingerprint or checksum algorithm name."},
    "allowlist": {"type": "list", "description": "List of path prefixes allowed for guarded destructive filesystem operations."},
    "denylist": {"type": "list", "description": "List of path prefixes refused for guarded destructive filesystem operations."},
    "any_of": {"type": "list", "description": "Allowed values for a check operation."},
    "append": {"type": "boolean", "default": False, "description": "Append supplementary groups instead of replacing the user group list."},
    "apply": {"type": "boolean", "default": False, "description": "Apply a generated system resource immediately after installation."},
    "archive": {"type": "path", "description": "Remote archive path to extract."},
    "atomic": {"type": "boolean", "default": True, "description": "Install generated file content via a temporary path and final rename where possible."},
    "body": {"type": "string", "description": "Raw HTTP request body."},
    "sensitive": {"type": "boolean", "default": False, "description": "Mask sensitive content in previews or logs."},
    "validate_before_reload": {"type": "boolean", "default": True, "description": "Validate service configuration before reload."},
    "match_blocks": {"type": "list", "description": "OpenSSH Match blocks to render."},
    "comment_update": {"type": "string", "description": "Authorized key comment to write."},
    "disablerepo": {"type": "list", "description": "Temporary repository to disable for package operation."},
    "enablerepo": {"type": "list", "description": "Temporary repository to enable for package operation."},
    "end": {"type": "string", "description": "End time for an audit search or time window."},
    "stats": {"type": "boolean", "default": False, "description": "Show transfer statistics."},
    "itemize_changes": {"type": "boolean", "default": False, "description": "Show per-file rsync changes."},
    "numeric_ids": {"type": "boolean", "default": False, "description": "Preserve numeric UID/GID values."},
    "partial": {"type": "boolean", "default": False, "description": "Keep partially transferred files."},
    "bwlimit": {"type": "integer", "min": 1, "description": "Bandwidth limit."},
    "reboot_required_check": {"type": "boolean", "default": False, "description": "Check whether reboot is required after package operation."},
    "download_only": {"type": "boolean", "default": False, "description": "Download packages without installing."},
    "security_only": {"type": "boolean", "default": False, "description": "Apply only security updates where supported."},
    "allow_downgrade": {"type": "boolean", "default": False, "description": "Allow explicit package downgrades."},
    "lock_after_install": {"type": "boolean", "default": False, "description": "Lock package after installation."},
    "no_recommends": {"type": "boolean", "default": False, "description": "Disable recommended dependencies where supported."},
    "protect_packages": {"type": "list", "description": "Packages that must not be removed."},
    "autoremove": {"type": "boolean", "default": False, "description": "Remove unused dependencies where supported."},
    "purge": {"type": "boolean", "default": False, "description": "Remove package configuration where supported."},
    "exclude": {"type": "list", "description": "Package or archive excludes."},
    "include_patterns": {"type": "list", "description": "Archive include patterns."},
    "checksum_verify": {"type": "string", "description": "Expected checksum for archive or file verification."},
    "safe_extract": {"type": "boolean", "default": True, "description": "Reject unsafe archive paths before extraction."},
    "match_count_assert": {"type": "integer", "description": "Expected number of regex matches."},
    "validate_command": {"type": "string", "description": "Command used to validate generated file content."},
    "fingerprint_assert": {"type": "string", "description": "Expected fingerprint value."},
    "exclusive": {"type": "boolean", "default": False, "description": "Keep only managed entries where supported."},
    "key_options": {"type": "string", "description": "SSH authorized_keys options prefix."},
    "to_port": {"type": "integer", "description": "Forward destination port."},
    "to_addr": {"type": "string", "description": "Forward destination address."},
    "timezone": {"type": "string", "description": "IANA timezone name."},
    "syscalls": {"type": "list", "description": "Audit syscall names."},
    "run_as": {"type": "string", "description": "sudo run-as target user."},
    "root": {"type": "path", "description": "Remote root directory for manifest or inventory operations."},
    "paths": {"type": "list", "description": "Relative paths selected for manifest or inventory operations."},
    "permissions": {"type": "string", "description": "Audit permissions such as rwa or wa."},
    "param": {"type": "string", "description": "Kernel command-line parameter."},
    "modules": {"type": "list", "description": "Module names."},
    "min_packets": {"type": "integer", "default": 1, "description": "Minimum firewall counter packet threshold."},
    "max_stratum": {"type": "integer", "default": 16, "description": "Maximum allowed NTP/chrony stratum."},
    "max_offset": {"type": "number", "default": 1.0, "description": "Maximum allowed NTP/chrony offset in seconds."},
    "max_lost": {"type": "integer", "default": 0, "description": "Maximum allowed audit lost-event count."},
    "max_backlog": {"type": "integer", "default": 8192, "description": "Maximum allowed audit backlog."},
    "include": {"type": "string", "description": "PAM include/substack target name."},
    "icmp_type": {"type": "string", "description": "firewalld ICMP type name."},
    "fragment": {"type": "string", "description": "Expected configuration or ruleset fragment."},
    "filters": {"type": "list", "description": "Audit rule filters such as auid>=1000."},
    "before": {"type": "string", "description": "Marker that must appear before another line or rule."},
    "after": {"type": "string", "description": "Marker that must appear after another line or rule."},
    "arch": {"type": "string", "default": "b64", "description": "CPU architecture selector for audit rules."},
    "backup_before": {"type": "boolean", "default": False, "description": "Capture or copy the current state before applying a potentially destructive change."},
    "check_only": {"type": "boolean", "default": False, "description": "Validate the requested change without applying it."},
    "persistent_file": {"type": "path", "description": "Persistent firewall configuration file to install after validation."},
    "position": {"type": "integer", "description": "Insertion position for ordered firewall rule backends."},
    "query_only": {"type": "boolean", "default": False, "description": "Query rule state without changing it."},
    "reload_mode": {"type": "string", "default": "none", "description": "Firewall reload behavior: none, reload or complete-reload."},
    "reload_service": {"type": "string", "description": "Service name to reload after installing persistent firewall configuration."},
    "save_after": {"type": "boolean", "default": False, "description": "Persist runtime firewall state after changing a rule."},
    "bits": {"type": "integer", "description": "Key size in bits when supported by the selected key type."},
    "baseurl": {"type": "string", "description": "Repository base URL for package manager repository files."},
    "enabled": {"type": "boolean", "default": True, "description": "Whether a repository or persistent resource is enabled."},
    "checks": {"type": "list", "description": "Health checks to run."},
    "engine": {"type": "string", "description": "Database engine such as sqlite, postgres, mysql or oracle."},
    "gpgcheck": {"type": "boolean", "default": True, "description": "Whether repository GPG checking is enabled."},
    "gpgkey": {"type": "string", "description": "Repository GPG key URL or path."},

    "devices": {"type": "list", "description": "Block devices to inspect."},
    "udev": {"type": "boolean", "default": True, "description": "Include udev properties when collecting facts."},
    "device": {"type": "path", "description": "Block device path."},
    "scsi_id_path": {"type": "path", "default": "/usr/lib/udev/scsi_id", "description": "Path to the scsi_id helper."},
    "udev_settle": {"type": "boolean", "default": True, "description": "Wait for udev events to settle after the operation."},
    "multipath_reload": {"type": "boolean", "default": False, "description": "Refresh multipath maps after the operation."},
    "label": {"type": "string", "description": "Disk label, filesystem label or partition label."},
    "partitions": {"type": "list", "description": "Desired partition entries for a storage.block.partition.apply operation."},
    "backup": {"type": "boolean", "default": False, "description": "Create a backup before modifying an existing file."},
    "backup_path": {"type": "path", "description": "Explicit backup path for pre-change file content."},
    "backup_suffix": {"type": "string", "default": ".bak", "description": "Suffix appended to the original path when backup is enabled."},
    "backup_existing": {"type": "boolean", "default": False, "description": "Create a backup of an existing destination before replacing it."},
    "confirm": {"type": "boolean", "description": "Explicit destructive-operation confirmation flag."},
    "content_checksums": {"type": "boolean", "default": True, "description": "Include per-file content checksums in generated backup manifests."},
    "older_than_days": {"type": "integer", "description": "Age threshold in days for pruning old backup artifacts."},
    "keep": {"type": "integer", "description": "Number of backup artifacts or rotated generations to retain."},
    "metadata_size": {"type": "string", "description": "LVM thin-pool metadata size."},
    "chunksize": {"type": "string", "description": "LVM thin-pool chunk size."},
    "acl": {"type": "string", "description": "POSIX ACL entry accepted by setfacl."},
    "attrs": {"type": "string", "description": "Linux filesystem attribute flags accepted by chattr."},
    "target": {"type": "string", "description": "Quota target user or group."},
    "mountpoint": {"type": "path", "description": "Mounted filesystem path."},
    "block_soft": {"type": "integer", "default": 0, "description": "Soft block quota."},
    "block_hard": {"type": "integer", "default": 0, "description": "Hard block quota."},
    "inode_soft": {"type": "integer", "default": 0, "description": "Soft inode quota."},
    "inode_hard": {"type": "integer", "default": 0, "description": "Hard inode quota."},
    "settings": {"type": "mapping", "description": "SSH client or server settings."},
    "match": {"type": "string", "description": "SSH Match clause."},
    "hosts": {"type": "string", "default": "ALL", "description": "sudoers hosts field."},
    "runas": {"type": "string", "default": "ALL", "description": "sudoers run-as field."},
    "commands": {"type": "list", "description": "Allowed sudo command list or ALL."},
    "nopassword": {"type": "boolean", "default": False, "description": "Whether to include NOPASSWD."},
    "cert": {"type": "path", "description": "Certificate path."},
    "key_dest": {"type": "path", "description": "Installed private key destination path."},
    "cert_dest": {"type": "path", "description": "Installed certificate destination path."},
    "untrusted": {"type": "path", "description": "Untrusted intermediate certificate chain file."},
    "ca_file": {"type": "path", "description": "CA bundle file path."},
    "config": {"type": "path", "description": "OpenSSL configuration file path."},
    "database": {"type": "path", "description": "SQLite database path or database name, depending on the plugin."},
    "command": {"type": "string", "description": "Command line to execute."},
    "comment": {"type": "string", "description": "User account comment or GECOS field."},
    "commit": {"type": "boolean", "default": True, "description": "Commit the database transaction on success; false rolls it back."},
    "compression": {"type": "string", "default": "auto", "description": "Archive compression: auto, none, gzip, bzip2 or xz."},
    "compress": {"type": "boolean", "default": False, "description": "Enable stream compression when supported."},
    "connect_timeout": {"type": "number", "default": 3, "min": 0, "description": "Per-attempt TCP connect timeout in seconds."},
    "connection": {"type": "mapping", "description": "Database connection mapping; values may be rendered from vars or secrets."},
    "contains": {"type": "string", "description": "Required substring in stdout or HTTP response body."},
    "content": {"type": "string", "description": "Text content to write."},
    "condition": {"type": "string", "description": "PAM condition expression, for example user ingroup wheel."},
    "control": {"type": "string", "description": "PAM control field such as required, requisite, sufficient or a bracketed control expression."},
    "count": {"type": "integer", "default": 0, "min": 0, "description": "Maximum regex replacements; 0 means replace all matches."},
    "create": {"type": "boolean", "default": False, "description": "Create the remote file when ensuring a line is present."},
    "create_home": {"type": "boolean", "description": "Create the user's home directory when supported by useradd."},
    "creates": {"type": "path", "description": "Remote path that makes the operation idempotent when already present."},
    "cwd": {"type": "path", "description": "Remote or local working directory for this operation."},
    "dest": {"type": "path", "description": "Destination path."},
    "extensions": {"type": "string", "description": "OpenSSL extension section name."},
    "days": {"type": "integer", "default": 365, "description": "Certificate validity in days."},
    "delete": {"type": "boolean", "default": False, "description": "Delete extraneous destination files when supported."},
    "rsync_path": {"type": "path", "description": "Remote rsync executable path."},
    "ssh_options": {"type": "list", "description": "Extra ssh options used by rsync."},
    "dry_run": {"type": "boolean", "default": False, "description": "Render or run without applying changes when supported."},
    "direction": {"type": "string", "default": "upload", "description": "Transfer direction such as upload, download or local."},
    "enable": {"type": "boolean", "default": False, "description": "Enable a service or timer after installing its unit."},
    "start": {"type": "boolean", "default": False, "description": "Start a service or timer after installing its unit."},
    "encoding": {"type": "string", "default": "utf-8", "description": "Text encoding used for command output, HTTP bodies or file content."},
    "env": {"type": "mapping", "description": "Environment variables for a local command."},
    "dump": {"type": "integer", "default": 0, "description": "fstab dump field."},
    "fstype": {"type": "string", "description": "Filesystem type such as xfs, ext4 or nfs."},
    "opts": {"type": "string", "default": "defaults", "description": "Mount options."},
    "passno": {"type": "integer", "default": 0, "min": 0, "description": "fstab fsck pass number."},
    "equals": {"type": "string", "description": "Expected stdout value after trimming whitespace."},
    "excludes": {"type": "list", "description": "Glob patterns excluded from archive creation."},
    "expected_status": {"type": "integer", "default": 200, "min": 100, "max": 599, "description": "Expected HTTP status code."},
    "fail_on_disabled": {"type": "boolean", "default": False, "description": "Fail when the queried service is not enabled."},
    "fail_on_inactive": {"type": "boolean", "default": False, "description": "Fail when the queried service is not active."},
    "fetch": {"type": "string", "default": "all", "description": "Database fetch mode: all, one or none."},
    "features": {"type": "list", "description": "Profile or backend feature flags."},
    "file": {"type": "path", "description": "Remote configuration file path."},
    "module": {"type": "string", "description": "Linux kernel module name."},
    "persist": {"type": "boolean", "default": False, "description": "Persist the change across reboots."},
    "runtime": {"type": "boolean", "default": True, "description": "Apply the change to the running system."},
    "value": {"type": "string", "description": "Desired parameter value."},
    "text": {"type": "string", "description": "Text payload for redaction scanning or assertion."},
    "force": {"type": "boolean", "default": False, "description": "Force the operation when supported."},
    "from": {"type": "string", "description": "Source address for firewall rules."},
    "permanent": {"type": "boolean", "default": True, "description": "Persist firewalld changes permanently."},
    "protocol": {"type": "string", "default": "tcp", "enum": ["tcp", "udp"], "description": "Network protocol such as tcp or udp."},
    "reload": {"type": "boolean", "default": False, "description": "Reload service configuration after a change."},
    "rich_rule": {"type": "string", "description": "firewalld rich rule expression."},
    "rule": {"type": "string", "description": "Firewall action such as allow, deny, reject or limit."},
    "to": {"type": "string", "description": "Destination address for firewall rules."},
    "tool": {"type": "string", "description": "Executable or tool name."},
    "tools": {"type": "list", "description": "Executable names required by a capability preflight."},
    "plugin": {"type": "string", "description": "Plugin name selected for requirements inspection."},
    "plugins": {"type": "list", "description": "Plugin names selected for requirements inspection."},
    "version_arg": {"type": "string", "default": "--version", "description": "Argument used to print a tool version."},
    "regex": {"type": "string", "description": "Regular expression expected in command output."},
    "trash_dir": {"type": "path", "description": "Remote directory used to move the target instead of deleting it."},
    "zone": {"type": "string", "description": "firewalld zone name."},
    "get_pty": {"type": "boolean", "default": False, "description": "Request a pseudo-terminal for the remote command."},
    "gid": {"type": "integer", "min": 0, "description": "Numeric group id."},
    "group": {"type": "string", "description": "Primary group, file group owner or remote group name."},
    "groups": {"type": "list", "description": "Supplementary group names."},
    "headers": {"type": "mapping", "description": "HTTP request headers."},
    "home": {"type": "path", "description": "User home directory."},
    "host": {"type": "string", "description": "Hostname or IP address to check from the controller."},
    "ignore_missing": {"type": "boolean", "default": True, "description": "Treat missing processes as success."},
    "interval": {"type": "number", "default": 2, "min": 0, "description": "Polling interval in seconds."},
    "retries": {"type": "integer", "default": 12, "min": 1, "description": "Maximum polling attempts before a wait operation fails."},
    "issuer": {"type": "string", "description": "Expected certificate issuer string."},
    "json": {"type": "mapping", "description": "JSON HTTP request body."},
    "key": {"type": "string", "description": "SSH public key line."},
    "password": {"type": "string", "description": "Plaintext password; prefer password_hash when possible."},
    "password_hash": {"type": "string", "description": "crypt(3) password hash passed to usermod --password."},
    "passphrase_secret": {"type": "string", "description": "Secret name containing a key passphrase."},
    "public_key_only": {"type": "boolean", "default": False, "description": "Only derive/read the public key instead of generating a new keypair."},
    "fingerprint": {"type": "boolean", "default": True, "description": "Emit a key or certificate fingerprint after the operation."},
    "validate": {"type": "boolean", "default": True, "description": "Validate generated or uploaded content before installing it."},
    "line": {"type": "string", "description": "Exact line to ensure in a remote file."},
    "lock": {"type": "boolean", "default": False, "description": "Lock the remote user account."},
    "manager": {"type": "string", "default": "auto", "enum": ["auto", "apt", "dnf", "yum", "zypper", "pacman"], "description": "Package manager: auto, apt, dnf, yum, zypper or pacman."},
    "max_depth": {"type": "integer", "min": 0, "description": "Maximum remote find traversal depth."},
    "method": {"type": "string", "default": "GET", "description": "HTTP request method."},
    "min_free_mb": {"type": "integer", "min": 0, "description": "Minimum free disk space in MiB."},
    "min_free_percent": {"type": "number", "description": "Minimum free disk percentage."},
    "missing_ok": {"type": "boolean", "default": False, "description": "Return success with exists=false when the path is missing."},
    "mode": {"type": "string", "description": "POSIX file mode, for example 0644 or 0755."},
    "multipath": {"type": "boolean", "default": False, "description": "Include multipath output when collecting block-device facts."},
    "name": {"type": "string", "description": "Package, user or group name."},
    "not_contains": {"type": "string", "description": "Substring that must not appear in stdout."},
    "output": {"type": "string", "default": "rows", "description": "Database output format: rows, scalar, json or none."},
    "overwrite": {"type": "boolean", "default": False, "description": "Replace an existing destination when supported."},
    "owner": {"type": "string", "description": "Remote file owner."},
    "packages": {"type": "list", "description": "Package names for package-manager operations."},
    "path": {"type": "path", "description": "Remote or local path, depending on the plugin."},
    "pattern": {"type": "string", "description": "Regex, process pattern or search pattern."},
    "profile": {"type": "string", "description": "AppArmor profile, authselect profile or profile file path."},
    "selinux_type": {"type": "string", "description": "SELinux file context type."},
    "patterns": {"type": "list", "description": "Find-name patterns to match."},
    "pid": {"type": "integer", "description": "Process id."},
    "port": {"type": "integer", "min": 1, "max": 65535, "description": "TCP port number."},
    "preserve": {"type": "boolean", "default": False, "description": "Preserve mode, ownership and timestamps when copying."},
    "preserve_times": {"type": "boolean", "default": False, "description": "Preserve source access and modification timestamps when transferring files."},
    "pty": {"type": "boolean", "default": False, "description": "Request a pseudo-terminal for command.remote.run."},
    "query": {"type": "string", "description": "SQL query to execute."},
    "query_params": {"type": "sequence", "description": "SQL bind parameters passed to the database driver."},
    "rc": {"type": "integer", "default": 0, "min": 0, "description": "Expected process return code."},
    "recursive": {"type": "boolean", "default": False, "description": "Recurse into directories."},
    "refuse_root_paths": {"type": "boolean", "default": True, "description": "Refuse high-risk root-level paths such as /, /etc, /usr and /var."},
    "require_recursive_for_directories": {"type": "boolean", "default": True, "description": "Fail early when the target is a directory and recursive=true is not set."},

    "rules": {"type": "list", "description": "Structured rule entries."},
    "subsystem": {"type": "string", "description": "udev subsystem filter."},
    "action": {"type": "string", "description": "udev action to trigger."},
    "expect_paths": {"type": "integer", "description": "Minimum expected multipath path count."},
    "remove_home": {"type": "boolean", "default": False, "description": "Remove the user's home directory when deleting an account."},
    "replacement": {"type": "string", "description": "Regex replacement text."},
    "repo": {"type": "string", "description": "Repository definition line or repo file content."},
    "update_cache": {"type": "boolean", "default": False, "description": "Refresh package manager metadata after changing repositories."},
    "service": {"type": "string", "description": "Service name, PAM service name or systemd unit depending on the plugin."},
    "service_files": {"type": "list", "description": "Explicit PAM service file paths to inspect or modify."},
    "services": {"type": "list", "description": "PAM service names to inspect or modify."},

    "size": {"type": "string", "description": "Size such as 16G for file-backed swap."},
    "entries": {"type": "list", "description": "Structured entries for limits or configuration files."},
    "files": {"type": "list", "description": "Target files to inspect or modify."},
    "ip": {"type": "string", "description": "IP address for a hosts entry."},
    "names": {"type": "list", "description": "Hostnames or aliases for a hosts entry."},
    "backend": {"type": "string", "description": "Operation backend such as auto, runtime, networkmanager, systemd-networkd, ifcfg, plain-file, systemd-resolved or resolvconf."},
    "nameservers": {"type": "list", "description": "Resolver nameserver addresses."},
    "search": {"type": "list", "description": "Resolver search domains."},
    "options": {"type": "list", "description": "Resolver options."},
    "servers": {"type": "list", "description": "NTP/chrony server names."},
    "variables": {"type": "mapping", "description": "Environment variables to set."},
    "scope": {"type": "string", "default": "step", "description": "Environment scope: step, user, global or file."},
    "wait": {"type": "boolean", "default": False, "description": "Wait for the operation to become reachable again when supported."},
    "delay": {"type": "integer", "default": 3, "description": "Initial delay in seconds."},
    "checksum": {"type": "string", "description": "Expected SHA256 checksum for a downloaded file."},
    "checksum_file": {"type": "path", "description": "Checksum sidecar file path."},
    "schedule": {"type": "string", "description": "Five-field cron schedule."},
    "shell": {"type": "boolean", "description": "Run a local command through the platform shell."},
    "signal": {"type": "string", "default": "TERM", "description": "Signal name or number sent to a process."},
    "source": {"type": "path", "description": "Remote source path to archive."},
    "src": {"type": "path", "description": "Source path."},
    "state": {"type": "string", "description": "Desired state such as present, absent, started or stopped."},
    "statements": {"type": "list", "description": "SQL statements executed in order inside one transaction."},
    "status": {"type": "integer", "description": "Expected HTTP status code alias."},
    "stdin": {"type": "string", "description": "Text written to remote command standard input."},
    "strip_components": {"type": "integer", "default": 0, "description": "Path components stripped while extracting a tar archive."},
    "subset": {"type": "list", "default": ["os", "network"], "description": "Fact subsets: os, network, packages, services."},
    "success_rc": {"type": "integer", "default": 0, "min": 0, "description": "Return code considered successful."},
    "sudo": {"type": "boolean", "default": False, "description": "Run the remote operation through sudo -n when supported."},
    "system": {"type": "boolean", "default": False, "description": "Create a system user or group."},
    "timeout": {"type": "number", "min": 0, "description": "Operation timeout in seconds."},
    "warning_days": {"type": "integer", "default": 30, "description": "Certificate expiry warning window in days."},
    "test_only": {"type": "boolean", "default": False, "description": "Validate without applying when supported."},
    "type": {"type": "string", "description": "Path type filter: path, file, directory, dir, symlink or any."},
    "types": {"type": "list", "description": "SSH key types or other typed values accepted by the plugin."},
    "uid": {"type": "integer", "min": 0, "description": "Numeric user id."},
    "uuid": {"type": "string", "description": "Filesystem or block-device UUID."},
    "unlock": {"type": "boolean", "default": False, "description": "Unlock the remote user account."},
    "url": {"type": "string", "description": "HTTP URL."},
    "user": {"type": "boolean", "default": False, "description": "Use systemctl --user instead of the system manager."},
    "validate_tls": {"type": "boolean", "default": True, "description": "Validate TLS certificates for HTTPS requests."},
    "values": {"type": "mapping", "description": "Additional template values exposed as values.*."},

    "vg": {"type": "string", "description": "LVM volume group name."},
    "resizefs": {"type": "boolean", "default": True, "description": "Resize the filesystem along with the block/LVM operation."},

    "address": {"type": "string", "description": "IP address to configure."},
    "prefix": {"type": "integer", "min": 0, "max": 128, "description": "CIDR prefix length."},
    "mtu": {"type": "integer", "description": "Network interface MTU."},
    "parent": {"type": "string", "description": "Parent network interface."},
    "nm_connection": {"type": "string", "description": "NetworkManager connection profile used for persistent DNS changes."},
    "vlan_id": {"type": "integer", "min": 1, "max": 4094, "description": "VLAN identifier."},
    "interfaces": {"type": "list", "description": "Network interfaces to include in a bond or aggregate."},
    "miimon": {"type": "integer", "default": 100, "description": "Bond link monitoring interval in milliseconds."},
    "stp": {"type": "boolean", "default": False, "description": "Enable STP on a Linux bridge when supported."},
    "gateway": {"type": "string", "description": "Route gateway address."},
    "dev": {"type": "string", "description": "Network device name for a route."},
    "table": {"type": "string", "description": "Routing table name or number."},
    "metric": {"type": "integer", "description": "Route metric."},

    "listen": {"type": "boolean", "default": True, "description": "Check whether a port is listening on the target."},

    "min_days": {"type": "integer", "default": 30, "description": "Minimum remaining certificate validity in days."},
    "update_trust": {"type": "boolean", "default": True, "description": "Refresh the system trust store after installing a CA certificate."},
    "update_grub": {"type": "boolean", "default": True, "description": "Regenerate GRUB configuration after modifying boot parameters."},
    "trust_store": {"type": "string", "default": "explicit", "description": "Trust-store mode: explicit path or system auto path."},

    "version": {"type": "string", "description": "Package version to pin."},
    "priority": {"type": "integer", "description": "Package repository or pin priority."},

    "max_count": {"type": "integer", "description": "Maximum number of matching log or process entries."},
    "min_count": {"type": "integer", "description": "Minimum number of matching process entries."},
    "max_percent": {"type": "integer", "description": "Maximum allowed percentage."},
    "max_used_percent": {"type": "number", "description": "Maximum allowed used percentage."},
    "wwid": {"type": "string", "description": "Multipath WWID."},
    "since": {"type": "string", "description": "Start time for journalctl queries."},
    "until": {"type": "string", "description": "End time for journalctl queries."},
    "lines": {"type": "integer", "default": 200, "description": "Number of log or journal lines to collect."},

    "subject": {"type": "string", "description": "Email subject line."},
    "smtp_host": {"type": "string", "description": "SMTP server host used by the Automax controller."},
    "smtp_port": {"type": "integer", "default": 587, "description": "SMTP server port."},
    "starttls": {"type": "boolean", "default": True, "description": "Use STARTTLS before SMTP authentication."},
    "ssl": {"type": "boolean", "default": False, "description": "Use implicit TLS for SMTP."},
    "username": {"type": "string", "description": "SMTP username; prefer values rendered from secrets."},
    "cc": {"type": "list", "description": "Email CC recipients."},
    "bcc": {"type": "list", "description": "Email BCC recipients."},
    "reply_to": {"type": "string", "description": "Email Reply-To address."},
    "attachments": {"type": "list", "description": "Local controller-side attachment paths."},
    "changed": {"type": "boolean", "default": True, "description": "Whether a successful command should be reported as changed."},
    "ipv6": {"type": "boolean", "default": False, "description": "Use IPv6 command variant when supported."},
    "chain": {"type": "string", "description": "Firewall chain name."},
    "family": {"type": "string", "default": "inet", "description": "nftables address family such as ip, ip6, inet, arp, bridge or netdev."},
    "handle": {"type": "boolean", "default": False, "description": "Include nftables rule handles when listing rules."},
    "numeric": {"type": "boolean", "default": True, "description": "Use numeric address and service output when supported."},
    "verbose": {"type": "boolean", "default": False, "description": "Include verbose firewall listing output when supported."},
    "policy": {"type": "string", "description": "Default firewall policy such as ACCEPT or DROP."},
}

OPTIONAL_PARAM_OVERRIDES: dict[str, tuple[str, ...]] = {
    "command.local.run": ("cwd", "env", "shell", "timeout", "success_rc", "changed"),
    "command.remote.run": ("cwd", "timeout", "pty", "stdin", "encoding", "success_rc", "changed"),
}

DEFAULT_RESULT_FIELDS = {
    "changed": "Whether the plugin changed the target or controller state.",
    "message": "Human-readable result message.",
    "rc": "Process or command return code when applicable.",
    "stdout": "Captured standard output when applicable.",
    "stderr": "Captured standard error when applicable.",
    "data": "Plugin-specific structured result data.",
}

RESULT_FIELD_OVERRIDES: dict[str, dict[str, str]] = {
    "storage.mount.bind": {"data.path": "Bind mount target path when returned by the implementation."},
    "storage.usage.disk_check": {"stdout": "df output used for the disk usage check."},
    "storage.usage.inode_check": {"stdout": "df -i output used for the inode usage check."},
    "fs.dir.exists": {"data.exists": "Boolean directory existence result.", "data.path": "Checked remote path.", "data.type": "Expected filesystem type."},
    "fs.file.exists": {"data.exists": "Boolean regular-file existence result.", "data.path": "Checked remote path.", "data.type": "Expected filesystem type."},
    "fs.symlink.exists": {"data.exists": "Boolean symlink existence result.", "data.path": "Checked remote path.", "data.type": "Expected filesystem type."},
    "fs.dir.wait": {"data.state": "Desired directory state.", "data.attempts": "Polling attempts used."},
    "fs.file.wait": {"data.state": "Desired regular-file state.", "data.attempts": "Polling attempts used."},
    "fs.symlink.wait": {"data.state": "Desired symlink state.", "data.attempts": "Polling attempts used."},
    "fs.object.stat": {"data.exists": "Boolean path existence result.", "data.size": "Path size in bytes.", "data.mode": "POSIX mode.", "data.owner": "Owner name.", "data.group": "Group name."},
    "fs.file.read": {"stdout": "Remote file content.", "data.path": "Read remote path."},
    "fs.file.template": {"data.src": "Rendered template path.", "data.dest": "Remote destination path"},
    "database.sqlite.check": {"data.engine": "Database engine checked.", "data.checks": "Boolean check results.", "data.latency_ms": "Measured health-check duration in milliseconds."},
    "database.sqlite.query": {"data.rows": "Fetched rows for SELECT-style statements.", "data.scalar": "First column of the first row when output=scalar.", "data.rowcount": "Driver rowcount when available."},
    "database.postgres.query": {"data.rows": "Fetched rows for SELECT-style statements.", "data.scalar": "First column of the first row when output=scalar.", "data.rowcount": "Driver rowcount when available."},
    "database.mysql.query": {"data.rows": "Fetched rows for SELECT-style statements.", "data.scalar": "First column of the first row when output=scalar.", "data.rowcount": "Driver rowcount when available."},
    "database.oracle.query": {"data.rows": "Fetched rows for SELECT-style statements.", "data.scalar": "First column of the first row when output=scalar.", "data.rowcount": "Driver rowcount when available."},
    "network.http.request": {"data.status": "HTTP response status code.", "data.body": "Decoded response body.", "data.headers": "Response headers."},
    "network.http.check": {"data.status": "HTTP response status code.", "data.body": "Decoded response body."},
    "network.http.wait": {"data.status": "HTTP response status code.", "data.body": "Decoded response body."},
    "network.connectivity.port_wait": {"data.host": "Checked host.", "data.port": "Checked TCP port."},
    "network.connectivity.port_check": {"data.host": "Checked host.", "data.port": "Checked TCP port."},
    "data.transfer.upload": {"data.src": "Local source path.", "data.dest": "Remote destination path"},
    "data.transfer.download": {"data.src": "Remote source path.", "data.dest": "Local destination path."},
    "data.transfer.rsync": {"data.command": "Executed rsync argument vector."},
    "identity.user.exists": {"data.exists": "Whether the remote user exists.", "data.name": "Checked username."},
    "identity.group.exists": {"data.exists": "Whether the remote group exists.", "data.name": "Checked group name."},
    "network.firewall.ufw.status": {"data.status": "Raw UFW status output."},
    "network.link.facts": {"data.links": "Network link facts from iproute2 JSON output."},
    "network.route.facts": {"data.routes": "Route facts from iproute2 JSON output."},
    "system.kernel.sysctl.get": {"data.name": "sysctl name.", "data.value": "Current sysctl value."},
    "system.kernel.sysctl.set": {"data.name": "sysctl name.", "data.value": "Desired sysctl value."},
    "security.apparmor.status": {"data.status": "Raw AppArmor status output."},
    "system.cron.entry.add": {"data.path": "Installed cron.d file path."},
    "system.cron.file": {"data.path": "Installed cron.d file path."},
    "os.facts": {"data.os": "Operating system facts."},
    "os.package.facts": {"data.packages": "Installed package facts."},
    "system.service.facts": {"data.services": "systemd service facts."},
    "security.sudo.dropin": {"data.path": "Installed sudoers drop-in path."},
    "data.transfer.sync": {"data.src": "Local source directory.", "data.dest": "Remote destination directory."},
}

SAMPLE_VALUES: dict[str, Any] = {
    "allow_replace_non_symlink": False,
    "algorithm": "sha256",
    "any_of": {"type": "list", "description": "Allowed values for a check operation."},
    "append": True,
    "archive": "/tmp/app.tar.gz",
    "body": "payload",
    "bits": 4096,
    "command": "echo automax",
    "comment": "Application user",
    "commit": True,
    "compression": "gzip",
    "connect_timeout": 3,
    "connection": {"path": "/tmp/automax.sqlite"},
    "contains": "ok",
    "content": "managed by automax\n",
    "count": 0,
    "create": True,
    "create_home": False,
    "creates": "/opt/app/.installed",
    "cwd": "/tmp",
    "dest": "/tmp/dest",
    "encoding": "utf-8",
    "env": {"DEMO": "1"},
    "dump": 0,
    "fstype": "xfs",
    "opts": "defaults,noatime",
    "passno": 0,
    "equals": "ok",
    "excludes": ["*.tmp"],
    "expected_status": 200,
    "fail_on_disabled": True,
    "fail_on_inactive": True,
    "fetch": "all",
    "file": "/etc/sysctl.d/99-automax.conf",
    "module": "br_netfilter",
    "persist": True,
    "runtime": True,
    "value": "1",
    "text": "password=secret",
    "force": True,
    "from": "10.0.0.0/8",
    "permanent": True,
    "protocol": "tcp",
    "reload": True,
    "rich_rule": "rule family=ipv4 source address=10.0.0.0/8 service name=ssh accept",
    "rule": "allow",
    "to": "any",
    "zone": "public",
    "get_pty": False,
    "gid": 2000,
    "group": "app",
    "groups": ["app"],
    "headers": {"Accept": "application/json"},
    "home": "/var/lib/app",
    "host": "127.0.0.1",
    "ignore_missing": True,
    "interval": 2,
    "retries": 3,
    "issuer": "CN=Example CA",
    "json": {"ok": True},
    "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDemo automax@example",
    "password": "secret-password",
    "password_hash": "$6$rounds=4096$salt$hash",
    "device": "/dev/sdb",
    "devices": ["/dev/sdb"],
    "scsi_id_path": "/usr/lib/udev/scsi_id",
    "udev": True,
    "udev_settle": True,
    "multipath_reload": True,
    "label": "gpt",
    "partitions": [{"number": 1, "name": "DATA01", "start": "1MiB", "end": "100%"}],
    "validate": True,
    "line": "KEY=value",
    "lock": True,
    "manager": "auto",
    "max_depth": 2,
    "method": "GET",
    "min_free_mb": 1024,
    "min_free_percent": 10,
    "missing_ok": True,
    "multipath": False,
    "mode": "0644",
    "name": "nginx",
    "not_contains": "error",
    "output": "rows",
    "overwrite": True,
    "owner": "app",
    "packages": ["curl"],
    "path": "/tmp/automax-demo",
    "pattern": "KEY=.*",
    "profile": "/etc/apparmor.d/usr.sbin.nginx",
    "selinux_type": "httpd_sys_content_t",
    "patterns": ["*.conf"],
    "pid": 1234,
    "port": 22,
    "preserve": True,
    "preserve_times": True,
    "pty": False,
    "query": "SELECT 1 AS value",
    "query_params": [],
    "rc": 0,
    "rules": [{"match": {"env": {"DM_UUID": "mpath-3600..."}}, "symlink": "disk/by-storage/DATA01", "owner": "root", "group": "disk", "mode": "0660"}],
    "subsystem": "block",
    "action": "change",
    "expect_paths": 4,
    "recursive": True,
    "remove_home": False,
    "replacement": "KEY=new-value",
    "repo": "deb [signed-by=/etc/apt/keyrings/vendor.gpg] https://repo.example stable main",
    "update_cache": True,
    "service": "sshd",
    "schedule": "*/5 * * * *",
    "shell": "/bin/bash",
    "signal": "TERM",
    "size": "16G",
    "entries": [{"domain": "appuser", "type": "soft", "item": "nofile", "value": 1024}],
    "condition": "user ingroup wheel",
    "control": "required",
    "service_files": ["/etc/pam.d/login"],
    "services": ["sshd"],
    "files": ["/etc/pam.d/login"],
    "ip": "192.0.2.10",
    "names": ["app1.example.com", "app1"],
    "backend": "auto",
    "nameservers": ["192.0.2.53"],
    "search": ["example.com"],
    "options": ["timeout:2"],
    "servers": ["time.example.com"],
    "variables": {"APP_HOME": "/opt/app"},
    "scope": "global",
    "wait": True,
    "delay": 3,
    "checksum": "0123456789abcdef",
    "source": "/var/log/app",
    "src": "/tmp/source",
    "state": "present",
    "statements": ["CREATE TABLE IF NOT EXISTS demo(id INTEGER)"],
    "status": 200,
    "stdin": "input\n",
    "strip_components": 1,
    "subset": ["os", "network"],
    "success_rc": 0,
    "sudo": True,
    "system": True,
    "timeout": 60,
    "type": "file",
    "types": ["ed25519"],
    "uid": 2000,
    "uuid": "11111111-2222-3333-4444-555555555555",
    "unlock": True,
    "url": "https://example.invalid/health",
    "user": "deploy",
    "validate_tls": True,
    "values": {"app_name": "demo"},

    "vg": "vg_app",
    "resizefs": True,

    "address": "192.0.2.10",
    "prefix": 24,
    "mtu": 1500,
    "parent": "eth0",
    "vlan_id": 100,
    "interfaces": ["eth1", "eth2"],
    "miimon": 100,
    "stp": False,
    "gateway": "192.0.2.1",
    "dev": "eth0",
    "table": "main",
    "metric": 100,

    "listen": True,

    "min_days": 30,
    "update_trust": True,

    "version": "1.2.3*",
    "priority": 1001,

    "max_count": 10,
    "since": "1 hour ago",
    "until": "now",
    "lines": 200,

    "subject": "Automax notification",
    "smtp_host": "smtp.example.com",
    "smtp_port": 587,
    "starttls": True,
    "ssl": False,
    "username": "automax@example.com",
    "cc": ["ops-cc@example.com"],
    "bcc": ["audit@example.com"],
    "reply_to": "ops@example.com",
    "attachments": ["/tmp/report.txt"],
    "changed": True,
    "family": "inet",
    "handle": True,
    "numeric": True,
    "verbose": False,
    "policy": "DROP",
}

PLUGIN_EXAMPLES: dict[str, str] = {
    "fs.file.template": "use: fs.file.template\nwith:\n  src: ./templates/app.conf.j2\n  dest: /etc/myapp/app.conf\n  mode: '0644'\n  sudo: true",
    "database.sqlite.query": "use: database.sqlite.query\nwith:\n  connection:\n    path: /tmp/automax.sqlite\n  query: SELECT 1 AS value\n  output: rows",
    "command.remote.run": "use: command.remote.run\nwith:\n  command: systemctl is-active sshd\n  success_rc: 0",
    "security.ssh.authorized_key.add": "use: security.ssh.authorized_key.add\nwith:\n  user: deploy\n  key: '{{ vars.deploy_public_key }}'\n  state: present\n  sudo: true",
    "security.sudo.dropin": "use: security.sudo.dropin\nwith:\n  name: deploy-myapp\n  content: 'deploy ALL=(root) /bin/systemctl restart myapp'\n  validate: true\n  sudo: true",
    "network.firewall.firewalld.port": "use: network.firewall.firewalld.port\nwith:\n  port: 443\n  protocol: tcp\n  zone: public\n  state: present\n  permanent: true\n  reload: true\n  sudo: true",
    "network.firewall.ufw.rule": "use: network.firewall.ufw.rule\nwith:\n  rule: allow\n  port: 22\n  protocol: tcp\n  from: 10.0.0.0/8\n  sudo: true",
    "network.firewall.firewalld.source": "use: network.firewall.firewalld.source\nwith:\n  source: 10.0.0.0/8\n  zone: public\n  state: present\n  sudo: true",
    "network.firewall.nftables.apply": "use: network.firewall.nftables.apply\nwith:\n  src: ./firewall/prod.nft\n  sudo: true",
    "system.kernel.sysctl.set": "use: system.kernel.sysctl.set\nwith:\n  name: net.ipv4.ip_forward\n  value: '1'\n  runtime: true\n  persist: true\n  file: /etc/sysctl.d/99-automax.conf\n  sudo: true",
    "system.kernel.module.load": "use: system.kernel.module.load\nwith:\n  name: br_netfilter\n  persist: true\n  sudo: true",
    "os.package.key.add": "use: os.package.key.add\nwith:\n  name: vendor\n  manager: apt\n  url: https://repo.example/key.gpg\n  sudo: true",
    "os.package.repo.add": "use: os.package.repo.add\nwith:\n  name: vendor\n  manager: apt\n  repo: deb [signed-by=/etc/apt/keyrings/vendor.gpg] https://repo.example stable main\n  update_cache: true\n  sudo: true",
    "security.selinux.boolean": "use: security.selinux.boolean\nwith:\n  name: httpd_can_network_connect\n  value: true\n  persist: true\n  sudo: true",
    "security.apparmor.profile": "use: security.apparmor.profile\nwith:\n  profile: /etc/apparmor.d/usr.sbin.nginx\n  state: enforce\n  sudo: true",
    "system.cron.entry.add": "use: system.cron.entry.add\nwith:\n  name: myapp-health\n  schedule: '*/5 * * * *'\n  user: root\n  command: /usr/local/bin/myapp-healthcheck\n  sudo: true",
    "os.facts": "use: os.facts\nwith:\n  subset:\n    - os\n    - network\n    - services",
    "security.password.policy": "use: security.password.policy\nwith:\n  name: hardening\n  settings:\n    minlen: 14\n    dcredit: -1\n    ucredit: -1\n    retry: 3\n  sudo: true",
    "storage.mount.add": "use: storage.mount.add\nwith:\n  src: /dev/vdb1\n  path: /data\n  fstype: xfs\n  opts: defaults,noatime\n  persist: true\n  sudo: true",
    "storage.fstab.add": "use: storage.fstab.add\nwith:\n  src: /dev/vdb1\n  path: /data\n  fstype: xfs\n  opts: defaults,noatime\n  sudo: true",
    "storage.usage.disk_check": "use: storage.usage.disk_check\nwith:\n  path: /var\n  min_free_mb: 1024\n  max_used_percent: 85\n  sudo: true",
    "storage.usage.inode_check": "use: storage.usage.inode_check\nwith:\n  path: /var\n  max_used_percent: 85\n  sudo: true",
    "storage.quota.set": "use: storage.quota.set\nwith:\n  type: user\n  target: app\n  mountpoint: /data\n  block_soft: 1000000\n  block_hard: 1200000\n  inode_soft: 10000\n  inode_hard: 12000\n  sudo: true",
    "storage.multipath.add": "use: storage.multipath.add\nwith:\n  wwid: '3600508b400105e210000900000490000'\n  reload: true\n  sudo: true",
    "command.local.run": "use: command.local.run\nwith:\n  command: echo automax\n  changed: false",
}


def apply_builtin_metadata(plugin: BasePlugin) -> BasePlugin:
    """Enrich a builtin plugin instance with complete public metadata."""
    optional_override = OPTIONAL_PARAM_OVERRIDES.get(plugin.name)
    if optional_override:
        plugin.optional_params = tuple(dict.fromkeys((*plugin.optional_params, *optional_override)))

    schema: dict[str, dict[str, Any]] = dict(getattr(plugin, "parameter_schema", {}) or {})
    for name in (*plugin.required_params, *plugin.optional_params):
        if name not in PARAMETERS:
            raise KeyError(f"missing metadata definition for parameter '{name}' used by {plugin.name}")
        merged = dict(PARAMETERS[name])
        merged.update(schema.get(name, {}))
        schema[name] = merged
    plugin.parameter_schema = schema

    result_fields = dict(DEFAULT_RESULT_FIELDS)
    result_fields.update(RESULT_FIELD_OVERRIDES.get(plugin.name, {}))
    plugin.result_fields = result_fields

    if not plugin.examples:
        plugin.examples = (_build_example(plugin),)
    return plugin


def _build_example(plugin: BasePlugin) -> str:
    configured = PLUGIN_EXAMPLES.get(plugin.name)
    if configured:
        return configured
    params = list(plugin.required_params)
    if not params:
        params = [name for name in plugin.optional_params[:2] if name in SAMPLE_VALUES]
    lines = [f"use: {plugin.name}"]
    if params:
        lines.append("with:")
        for name in params:
            lines.extend(_format_sample_value(name, SAMPLE_VALUES.get(name, "value"), indent="  "))
    return "\n".join(lines)


def _format_sample_value(name: str, value: Any, *, indent: str) -> list[str]:
    if isinstance(value, bool):
        return [f"{indent}{name}: {str(value).lower()}"]
    if isinstance(value, (int, float)):
        return [f"{indent}{name}: {value}"]
    if isinstance(value, list):
        lines = [f"{indent}{name}:"]
        lines.extend(f"{indent}  - {item}" for item in value)
        return lines
    if isinstance(value, dict):
        lines = [f"{indent}{name}:"]
        for key, item in value.items():
            if isinstance(item, bool):
                rendered = str(item).lower()
            else:
                rendered = str(item)
            lines.append(f"{indent}  {key}: {rendered}")
        return lines
    return [f"{indent}{name}: {value}"]
